### ISSUE TITLE
scripts/bash/sshbl_deny.sh中curl获取压缩包建议加入-L参数

### ISSUE THREAD

**Issue by a951902402** [zhangnq/scripts#2]
在国外的VPS上（我的是韩国节点）运行此脚本，会提示如下错误
[root@localhost ~]# ./sshbl_deny.sh 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cat: zhangnq_sshbl_deny.txt: No such file or directory

之后采用wget方式单独运行curl一步发现网址会进行重定向如下
[root@localhost ~]# wget http://www.chekiang.info/scan/html/zhangnq_sshbl_deny.tar.gz
--2022-06-08 08:56:30--  http://www.chekiang.info/scan/html/zhangnq_sshbl_deny.tar.gz
Resolving www.chekiang.info (www.chekiang.info)... 47.244.192.46
Connecting to www.chekiang.info (www.chekiang.info)|47.244.192.46|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.chekiang.info/scan/html/zhangnq_sshbl_deny.tar.gz [following]
--2022-06-08 08:56:30--  https://www.chekiang.info/scan/html/zhangnq_sshbl_deny.tar.gz
Connecting to www.chekiang.info (www.chekiang.info)|47.244.192.46|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.nbhao.org/scan/html/zhangnq_sshbl_deny.tar.gz [following]
--2022-06-08 08:56:31--  http://www.nbhao.org/scan/html/zhangnq_sshbl_deny.tar.gz
Resolving www.nbhao.org (www.nbhao.org)... 172.67.206.57, 104.21.74.200, 2606:4700:3030::6815:4ac8, ...
Connecting to www.nbhao.org (www.nbhao.org)|172.67.206.57|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5215 (5.1K) [application/octet-stream]
Saving to: ‘zhangnq_sshbl_deny.tar.gz’

100%[======================================================================================================>] 5,215       --.-K/s   in 0s      

2022-06-08 08:56:31 (1.01 GB/s) - ‘zhangnq_sshbl_deny.tar.gz’ saved [5215/5215]

后在脚本中对curl加入-L参数后，脚本运行正常

**Comment by zhangnq** [comment]
获取地址修改，https://www.nbhao.org/scan/html/zhangnq_sshbl_deny.tar.gz
